BBBBBBB BBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB

    BBBBB BBBBBXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXX XXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXX
            XXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 #

                 #
 #
 #
 #
 #

                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXX XX XXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFF
                    
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX
                    
                XXXXXX

                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XX XXXX XXXX XXXX
                XXXX
                XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
                XXXXX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBB
    XXXX XXXXXX XXXXXX XXXX XXXXXXXXX XXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBB