BBBBBBB BBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB

    XXXX XXXXXXXXX XXX XXX
    BBBBB BBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    BBBBBBBB BBB

    BBBBB BBBBBXXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXX XXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXX BBB BBBBBBBBBBBBBBBBXX
                BBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXX XXXXX XXXXX XX XXXXXXXX XX XXXX XXXXXX XXX XXXX XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBB
    XXXX XXXXXX XXXXXX XXXX XXXXXXXXX XXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBB