BBBBBBB BBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB

    XXXX XXXXXXXXX XXX XXX
    BBBBB BBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    BBBBBBBB BBB

    BBBBB BBBBBXXXX XXXXXXXXBBBBBBBB BBBBB


BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXX XXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXX
            XXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                 #

                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        FFFFFFFFFFFFFFFFFFFFFFFF
                        
                    XXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
            XXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXX XXXXX XXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXXX XXXX XXXXXXXXX XXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB


