BBBB BBBBBB
XXXXXXX
XX XXXXXXXX XX
    XXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXX XXXXXX X XXXXXX XX
    X

    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXX XX X
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXX
        XXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXX X X
        XXXXXX XXXXX
        XXXXXXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXX
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXX X XXXX XXXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXX XXXXXXXX
XXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                         #
 #
 #

                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXX XXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXX X XXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBXX XXXX XX XX XXXXXXXXX
                        XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                        
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX
XXXX XXXXXX XXXXXX