
XXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX 
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX
                                XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX
                            XXX XXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                                XX XXXXXXXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFXXXXXX
                            XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX
                                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBB
                                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                                    FFFFFFFFFFFFFFFFFFFFF
                                XXXXXXX
                                BBBBB
                            XXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXX
                                     XX XXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXX
                                     XX XXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXX XXX XXXXXXXX
                                     XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
                                     BB BBBBBBBBBBBBBBBBBBBBB
                                        XX XXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXX
                                     BBBBB
                                XXXXX
                            XXXXX
                        XXXXX
                        
                        BB BBB BBBBBBBBBBBBBBBBBBBBB
                             XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX
                         BBBBB
                    XXXXX
                XXXXXX

            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX