# Generated by Django 5.2.4 on 2025-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(default=3241399966, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
