# Generated by Django 5.2.4 on 2025-07-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='09384574466', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
