BBBBBBB BBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
BBBBBBBB BBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXX XXXX XXXXXXX
        XXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XX XXXX XX XXXX XXXXXXXX
            XXX
                XX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXX XXXXXX XXXXX XXX XX XXXXXXX XXXXX XXXXX XXXX XX XXXXX XXX XX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX X XXXXX XXXX XX XXXX XXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX XXXX XXXXXX XX XX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XX XX XXX XXXX XXXX XXX XX XXXXXXXXXX XXXXXXXX XX XXXXX XXXX XX XX XXXX XXXXXXXX XXXX XXXXXXXXX XXXXXX XX XXXXXX XX XXXXX XXXXXXXXX XXXXX XXXXXXX XXXXX XXX XX XXXXXX X XXXXX XXXX XXXXXXXXXXXX
            XXXX
        XXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XX XXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXX
                    XXXXX XX XXXX XX XXXX XXXXX XXXXXXXXX XXXXX XX XXXX XXXXXX XX XXXX XX XXXXX XXXXXX XXX XXX XX XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XX XXXXXXXXXX
                    XXXXX XXXXX XX XXXXXXX XXXXX XX XXX XXXX XXXX XXXXX XX XX XXXXXXXXX XXXX X XXXXXXX XXXXXX XXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX XX XXXX XXXXXXXXX
                    XXXXXXXXXXX XXXXXX XXX XXXXXX XXXXXX XX XXXXX XXXXX XX XXXXXXXX XXXXX XX XX XXXX XXXX XX XXXXXXX XXX XXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXX XX XXXXXXXXXXXXX
            XXXXXX XXXX XXX XXX XXXX XX XXX XXXX XXXXXXX XX XXXX XX XXXXXX XX XXXXXX XXXXXXX XX XX XXX XXXX X XX XXXXXXX XXXX XX XXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXXXXXXXX

    XXXXXX
BBBBBBBB BBBBBBB