BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
    XXXXXXXBBBBB BBBBBBBBBBBBB BBBBBXXXXXXXX

    
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX

    
    BBBBB BBB
    BBBBBBBB BBB
XXXXXXX
XXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

    XXXXXX
        
        BBBBB BBBBBBB
        BBBBBBBB BBBBBBB
    XXXXXXX
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB


    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXX
                XXX XXXXXX X XXXXXXXX
                XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXX X XBBB BBBBBBBBBBBBBBBBBXX
                XXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXX XXXX
                    XXXXX X
                        XXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX XX
                    XX
                    XXXXXXXX XXXXXXXXXXXXXXXXXX X
                        XX XXXXXXXXXXXXXXXX XXX XXXXXXXX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                        X XXXX XX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        X
                    XX
                    XXXXXX XXXXXXXXXXXXX X
                        XX XXXXXXXXXXX XXX XXXX X
                            XXXXXXXXXXX XXXX XXXXXX XXXXX XX XXXX XXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXX XXX XXXXXXXX
                        X XXXX X
                            XXXXXXXXXXXX XX XXXX XXXX XXXXXX XXXX XXXXXXXX
                        X
                    X
                XXX
            XXX
        XXX
    XXXXXXXXX
    
    XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX X XXXXXXXXXX
                XX XXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
                X
            XX XXXXXX
        XXX
    XXX
    XXXXXXXXX

    BBBBB BBBBBBBBBBBBBBB BBBBBBB

XXXXXXX
XXXXXXX